version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    rebase-strategy: auto
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    target-branch: "lxml-6.1"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    rebase-strategy: auto
    groups:
      github-actions:
        patterns:
          - "*"
