<?
$rss = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>
<rss version=\"2.0\">
  <channel>
    <title>Chromewaves</title>
    <link>http://www.chromewaves.net</link>
    <description></description>
    <language>en-us</language>
    <docs>http://blogs.law.harvard.edu/tech/rss</docs>
    <generator>RSS2.0 for Nucleus by crankycoder.com</generator>

    <managingEditor>frank@chromewaves.net</managingEditor>
    <webMaster>frank@chromewaves.net</webMaster>


    <item>
     <title>Take The Fifth</title>
     <link>http://www.chromewaves.net/?itemid=1473</link>
     <description>  &lt;img src=&quot;http://www.chromewaves.net/images/interface/spoonStudio.jpg&quot; title=&quot;Spoon in the studio&quot; class=&quot;blogPhoto&quot;&gt;&lt;A href=&quot;http://www.spoontheband.com/site.html&quot; target=&quot;new&quot; title=&quot;Spoon&quot;&gt;Spoon&lt;/a&gt; have finished recording their next record - finally - and have posted a mostly final tracklisting:&lt;br /&gt;
&lt;br /&gt;
The Infinite Pet&lt;br /&gt;
The Two Sides Of Monsieur Valentine&lt;br /&gt;
The Delicate Place&lt;br /&gt;
Was It You?&lt;br /&gt;
My Mathematical Mind&lt;br /&gt;
I Turn My Camera On&lt;br /&gt;
Sister Jack&lt;br /&gt;
I Summon You&lt;br /&gt;
Merchants Of Soul&lt;br /&gt;
The Beast And Dragon Adored&lt;br /&gt;
They Never Got You&lt;br /&gt;
&lt;br /&gt;
This isn't a final running order, there's no finalized title  (&lt;i&gt;The Beast And Dragon Are Adored&lt;/i&gt; was the last nominee) and no release date (I've got February written down but who knows).  So really, there isn't anything especially useful in THIS news blurb either.  I'm sensing a trend here.  There are some nice studio photos on the band's website, however, and a gallery courtesy of Britt's watchcam.  Tip-off from &lt;a href=&quot;http://www.catbirdseat.org/catbirdseat/&quot; Target=&quot;new&quot; title=&quot;Catbirdseat&quot;&gt;Catbirdseat&lt;/a&gt;, who also has some artwork suggestions for the new record.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.billboard.com/bb/daily/article_display.jsp?vnu_content_id=1000670986&quot; target=&quot;new&quot; title=&quot;Billboard vs Flaming Lips&quot;&gt;&lt;i&gt;Billboard&lt;/i&gt;&lt;/a&gt; gets not a lot of useful information from Wayne Coyne of &lt;a href=&quot;http://www.flaminglips.com&quot; target=&quot;new&quot; title=&quot;Flaming Lips&quot;&gt;The Flaming Lips&lt;/a&gt; about another of 2005's big releases, their next record &lt;i&gt;At War With The Mystics&lt;/i&gt;, and their eternally ongoing movie project &lt;i&gt;Christmas On Mars&lt;/i&gt;.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.popmatters.com/music/interviews/metric-041013.shtml&quot; target=&quot;new&quot; title=&quot;Popmatters&quot;&gt;PopMatters&lt;/a&gt; grills Emily Haines of &lt;a href=&quot;http://www.ilovemetric.com&quot; target=&quot;new&quot; title=&quot;Metric&quot;&gt;Metric&lt;/a&gt; about the creative process, cultural identity and being a sex symbol (in an interesting junction of the two topics, Haines was recently voted sexiest female Canadian musician by &lt;a href=&quot;http://www.chartattack.com&quot; target=&quot;new&quot; title=&quot;Chart&quot;&gt;&lt;i&gt;Chart&lt;/i&gt;&lt;/a&gt;).  From &lt;a href=&quot;http://blog.largeheartedboy.com&quot; target=&quot;new&quot; title=&quot;LHB&quot;&gt;Largehearted Boy&lt;/a&gt;.&lt;br /&gt;
&lt;br /&gt;
In what's becoming an annual tradition, &lt;a href=&quot;http://www.thesadies.net&quot; target=&quot;new&quot; title=&quot;The Sadies&quot;&gt;The Sadies&lt;/a&gt; will be rocking in the New Year December 31 at the Horseshoe.  Oh God, did I just say, &quot;Rocking in the New Year&quot;?  That's it.  I quit.&lt;br /&gt;
&lt;br /&gt;
I would like to say that this week has been a STRUGGLE for finding content.  Like fighting off rabid hamsters with a whiffle bat.  Some weeks these things write themselves.  This is not one of those weeks.  That is all.&lt;br /&gt;
&lt;br /&gt;
np - &lt;a href=&quot;http://www.doves.net&quot; target=&quot;new&quot; title=&quot;Doves&quot;&gt;Doves&lt;/a&gt; / &lt;i&gt;The Last Broadcast&lt;/i&gt; </description>
     <pubDate>Thu, 14 Oct 2004 09:27:45 EST</pubDate>
     <guid>http://www.chromewaves.net/?itemid=1473</guid>
</item>
<item>
     <title>Now At Last</title>
     <link>http://www.chromewaves.net/?itemid=1471</link>
     <description>  &lt;img src=&quot;http://www.chromewaves.net/images/interface/feist2.jpg&quot; title=&quot;Feist&quot; class=&quot;blogPhoto&quot;&gt;Six months after her carpet-bombing of Toronto during &lt;a href=&quot;http://www.nxne.com&quot; target=&quot;new&quot; title=&quot;NXNE&quot;&gt;NXNE&lt;/a&gt; (three shows in three nights), &lt;a href=&quot;http://feistmusic.artistes.universalmusic.fr/&quot; target=&quot;new&quot; title=&quot;Feist&quot;&gt;Feist&lt;/a&gt; returns to play the Phoenix on December 2. I'm not sure if I'll go to this one, I'm damn near concert-ed out for the year, but I recommend the show to anyone else.  I wonder what sort of band configuration she'll be playing with?  I can't find any other details yet - when I did a Google search for &quot;Feist Phoenix Toronto&quot;, I got my own site.  Sigh.  Thanks to &lt;a href=&quot;http://www.morecowbell.net&quot; target=&quot;new&quot; title=&quot;More Cowbell&quot;&gt;More Cowbell&lt;/a&gt; for the tip.&lt;br /&gt;
&lt;br /&gt;
You can download &quot;Ageless Beauty&quot;, the first single from &lt;a href=&quot;http://www.arts-crafts.ca/stars/&quot; target=&quot;new&quot; title=&quot;Stars&quot;&gt;Stars'&lt;/a&gt; new album &lt;i&gt;Set Yourself On Fire&lt;/i&gt;, &lt;a href=&quot;http://www.arts-crafts.ca/stars/freedownload/index.asp&quot; target=&quot;new&quot; title=&quot;Stars download&quot;&gt;here&lt;/a&gt;.  Word is this record is much more 'rock' than &lt;i&gt;Heart&lt;/i&gt; or &lt;i&gt;Night Songs&lt;/i&gt; - the single is nice, but I like hearing Amy sing pretty much anything.  The album is already out in Canada but the rest of the world will have to wait until early '05.  Or you can order it from &lt;a href=&quot;http://www.amazon.ca/exec/obidos/ASIN/B00061F8M8/qid%3D1097673722/702-0584922-2252026&quot; target=&quot;new&quot; title=&quot;Stars @ Amazon&quot;&gt;Amazon.ca&lt;/a&gt; for $16.99.  Borders be damned!&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.mercuryrev.com&quot; target=&quot;new&quot; title=&quot;Mercury Rev&quot;&gt;Mercury Rev's&lt;/a&gt; new album is finally complete.  According to &lt;a href=&quot;http://au.v2music.com/site/actBio.asp?ID=23&quot; target=&quot;new&quot; title=&quot;Mercury Rev bio&quot;&gt;their new official bio&lt;/a&gt;, &quot;If &lt;i&gt;Deserter's Songs&lt;/i&gt; was Autumn, and &lt;i&gt;All Is Dream&lt;/i&gt; winter, then &lt;i&gt;The Secret Migration&lt;/i&gt; feels like spring: fresh-cheeked, maybe a little mischievous, infused with hopeful spirits&quot;.  Aww, sounds darling.  &lt;i&gt;The Secret Migration&lt;/i&gt; (if you didn't catch the album title) will be out January 25.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.steveearle.com&quot; target=&quot;new&quot; title=&quot;Steve Earle&quot;&gt;Steve Earle&lt;/a&gt; tells &lt;a href=&quot;http://www.billboard.com/bb/daily/article_display.jsp?vnu_content_id=1000664259&quot; target=&quot;new&quot; title=&quot;Billboard vs Steve Earle&quot;&gt;&lt;i&gt;Billboard&lt;/i&gt;&lt;/a&gt; why it's so crucial that Americans vote in the upcoming election and mentions that touring to support &lt;i&gt;The Revolution Starts... Now&lt;/i&gt; will continue in North America early next year.&lt;br /&gt;
&lt;br /&gt;
&lt;A href=&quot;http://www.filter-mag.com/news/interior.1795.html&quot; tar get=&quot;new&quot; title=&quot;Slint re-form&quot;&gt;The big news&lt;/a&gt; around indie-world is that &lt;A href=&quot;http://www.southern.com/southern/band/SLINT/&quot; target=&quot;new&quot; title=&quot;Slint&quot;&gt;Slint&lt;/a&gt; have reformed and will be curating the &lt;A href=&quot;http://www.atpfestival.com/&quot; target=&quot;new&quot; title=&quot;ATP&quot;&gt;All Tomorrow's Parties&lt;/a&gt; festival in the UK next February.  While I own &lt;i&gt;Spiderland&lt;/i&gt;, that was a mandatory hipster purchase more than anything else - it's definitely interesting if disquieting listening, but I don't spin it very often.&lt;br /&gt;
&lt;br /&gt;
I don't usually post anything from the plethora of unsolicited mp3s I'm sent as I fear that will just lead to more unsolicited mp3s, but this one is too bizarre not to let loose onto the world.  It's by a guy named &lt;a href=&quot;http://www.d-bo.com/&quot; target=&quot;new&quot; title=&quot;David Boyle&quot;&gt;David Boyle&lt;/a&gt; who... hell, I can't even begin to try and explain it cause I don't actually understand it.  but check out his website, check out &lt;A href=&quot;http://s91618919.onlinehome.us/GeorgeWPussy.mp3&quot; title=&quot;George W Pussy&quot;&gt;the mp3 he sent me&lt;/a&gt; and... well, you tell me.  &lt;a href=&quot;http://newflux.blogspot.com/2004/10/i-thought-youd-fallen-off-edge-of.html&quot; target=&quot;new&quot; title=&quot;Fluxblog&quot;&gt;Fluxblog&lt;/a&gt; also got sent a copy of the song (and I thought I was special!) and he's also posted an excerpt from the email that came with the file.  There's also a big discussion going on at &lt;a href=&quot;http://ilx.p3r.net/thread.php?msgid=5119921&quot; target=&quot;new&quot; title=&quot;ILM vs David Boyle&quot;&gt;ILX&lt;/a&gt; and the lyrics have been posted as well.  Words fail.  I'm a little ashamed of myself for biting and helping out the guy's obvious ploy at becoming some sort of flash-in-the-pan internet phenomenon, but it's a slow news day, okay?&lt;br /&gt;
&lt;br /&gt;
np - &lt;a href=&quot;http://www.mercuryrev.com&quot; target=&quot;new&quot; title=&quot;Mercury Rev&quot;&gt;Mercury Rev&lt;/a&gt; / &lt;i&gt;All Is Dream&lt;/i&gt; </description>
     <pubDate>Wed, 13 Oct 2004 09:35:18 EST</pubDate>
     <guid>http://www.chromewaves.net/?itemid=1471</guid>
</item>
<item>
     <title>Ghost Wiring</title>
     <link>http://www.chromewaves.net/?itemid=1469</link>
     <description>  &lt;img src=&quot;http://www.chromewaves.net/images/interface/nekoCase2.jpg&quot; title=&quot;Neko Case&quot; class=&quot;blogPhoto&quot;&gt;&lt;A href=&quot;http://www.mintrecs.com/bands/speak/neko/neko2003.html&quot; target=&quot;new&quot; title=&quot;Mint Records vs Neko Case&quot;&gt;Mint Records'&lt;/a&gt; new official &lt;a href=&quot;http://www.nekocase.com&quot; target=&quot;new&quot; title=&quot;Neko Case&quot;&gt;Neko Case&lt;/a&gt; bio details the rationale for and making of her new live album &lt;i&gt;The Tigers Have Spoken&lt;/i&gt;, out November 9.  She says that she deliberately wanted to make a more vibrant, positive-sounding record to contrast her darker, torchier stuff.  &quot;When we play,&quot; says Neko, &quot;people always come up and say, 'Are you going to do some upbeat stuff? Are you ever going to bring a drummer?' This record's sort of for them.&quot; Having attended one of the seven shows that was recorded to produce this album, I'm very excited to hear the finished product.  If the streaming sample track provided on the website is any indication, it's going to be an amazing record.  Her new studio record should be out next Spring.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.gothamist.com/archives/2004/10/11/ted_leo_in.php&quot; target=&quot;new&quot; title=&quot;Gothamist vs Ted Leo&quot;&gt;Gothamist&lt;/a&gt; finds out about &lt;a href=&quot;http://www.tedleo.com&quot; target=&quot;new&quot; title=&quot;Ted Leo&quot;&gt;Ted Leo's&lt;/a&gt; New York City.  Thanks to &lt;a href=&quot;http://therealjanelle.typepad.com/&quot; target=&quot;new&quot; title=&quot;The Real Janelle&quot;&gt;The Real Janelle&lt;/a&gt; for sending me the link.&lt;br /&gt;
&lt;br /&gt;
The new &lt;a href=&quot;http://www.thebandivy.com&quot; target=&quot;new&quot; title=&quot;Ivy&quot;&gt;Ivy&lt;/a&gt; record is complete and has a release date scheduled for February 1.  No title or tracklisting yet, but they hope to have some samples up on their website sooner rather than later.  The band has also contributed a cover of &quot;A Peanuts Christmas&quot; to this year's &lt;a href=&quot;http://www.nettwerkamerica.com&quot; target=&quot;new&quot; title=&quot;Nettwerk&quot;&gt;Nettwerk&lt;/a&gt; Christmas album.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.constantines.ca&quot; target=&quot;new&quot; title=&quot;The Constantines&quot;&gt;The Constantines&lt;/a&gt; are playing a double-header at Lee's Palace on November 27 - one all-ages matinee and a licensed evening show.  Because, obviously, they are fun for the whole family.  Pick Grandma up at the rest home and bring a picnic lunch.&lt;br /&gt;
&lt;br /&gt;
Sam Raimi tells &lt;a href=&quot;http://www.superherohype.com/news/featuresnews.php?id=2088&quot; target=&quot;new&quot; title=&quot;Superhero Hype&quot;&gt;Superhero Hype&lt;/a&gt; that the &lt;i&gt;Spider-Man&lt;/i&gt; franchise will likely wrap after the third film (for the best, I say - quit while you're ahead) and discusses the extra 30-40 seconds of action footage he wants to add to the &lt;i&gt;Spider-Man 2.5&lt;/i&gt; DVD that'll come out early next year.  The non-special, integer edition DVD is out end of next month.&lt;br /&gt;
&lt;br /&gt;
Just noticed that &lt;A href=&quot;http://ryan-adams.com/default.asp&quot; Target=&quot;new&quot; title=&quot;Ryan Adams&quot;&gt;Ryan Adams'&lt;/a&gt; &quot;My Hand Ain't Broke No More So I Can Give Jim DeRogatis The Finger&quot; tour will also be coming through Chicago the same weekend I will be there, as will the &lt;a href=&quot;http://www.pixiesmusic.com&quot; target=&quot;new&quot; title=&quot;Pixies&quot;&gt;Pixies&lt;/a&gt; cash-grab roadshow.  I've already got my &lt;A href=&quot;http://www.fuzzywuzzy.com&quot; target=&quot;new&quot; title=&quot;Luna&quot;&gt;Luna&lt;/a&gt; and &lt;A href=&quot;http://www.americanmusicclub.com&quot; target=&quot;new&quot; title=&quot;AMC&quot;&gt;American Music Club&lt;/a&gt; tickets and those were my absolute first choices for both nights anyways, but wow that's a lot of good shows to pick from for one weekend.&lt;br /&gt;
&lt;br /&gt;
np - &lt;A href=&quot;http://www.old97s.com&quot; target=&quot;new&quot; title=&quot;Old 97's&quot;&gt;Old 97's&lt;/a&gt; / &lt;i&gt;Wreck Your Life&lt;/i&gt; </description>
     <pubDate>Tue, 12 Oct 2004 09:19:03 EST</pubDate>
     <guid>http://www.chromewaves.net/?itemid=1469</guid>
</item>
<item>
     <title>Dead Smile</title>
     <link>http://www.chromewaves.net/?itemid=1468</link>
     <description>  &lt;img src=&quot;http://www.chromewaves.net/images/interface/christopherReeve.jpg&quot; title=&quot;Christopher Reeve&quot; class=&quot;blogPhoto&quot;&gt;&lt;A href=&quot;http://www.cnn.com/2004/SHOWBIZ/Movies/10/11/obit.reeve.ap/index.html&quot; target=&quot;new&quot; title=&quot;Christopher Reeve, RIP&quot;&gt;RIP, Christopher Reeve&lt;/a&gt;.  You fought one hell of a good fight.&lt;br /&gt;
&lt;br /&gt;
So everyone has been telling me to go see &lt;i&gt;Shaun Of The Dead&lt;/i&gt;.  And I had my reservations, I thought from the trailers that it looked like a thin-concept low-budget flick but its boosters insisted it was really clever, funny, scary and original.  Turns out we were both right.  It's absolutely a novel concept - protagonist and his overweight slothful buddy fight through a city of zombies to rescue his mom and ex-girlfrined - with decent production values and some genuinely clever bits, but it was also a pretty thin film.  After playing up the comedy angle for the first two-thirds of the film, it finally runs out of clever and tries to play up the horror side after realizing that there's simply not much humour left in the characters' situation.&lt;br /&gt;
&lt;br /&gt;
I was personally annoyed about a) how stupid all the characters got during the final act, seemingly forgetting EVERYTHING they'd learned to survive that far and b) how the zombies were so inconsistent in following the basic rules of zombie-ness.  I realize that criticizing something as deliberately slight as this film is rather silly, but my basic criteria for good movie vs bad movie tend to be pretty firm no matter what I'm watching.  But overall, it was alright and enjoyable, but not all that.  And as for all this talk of it springing a new genre of &quot;rom zom com&quot; (romantic zombie comedy) - I certainly hope not.  They barely got enough mileage out of the concept for one movie, there sure as hell isn't enough in the tank for any more.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.pitchforkmedia.com/record-reviews/a/american-music-club/love-songs-for-patriots.shtml&quot; target=&quot;new&quot; title=&quot;PF vs AMC&quot;&gt;Pitchfork&lt;/a&gt; agrees with me that the new &lt;a href=&quot;http://www.americanmusicclub.com&quot; target=&quot;new&quot; title=&quot;AMC&quot;&gt;American Music Club&lt;/a&gt; album is excellent, as well they should.  Because it is.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.interpolny.com&quot; target=&quot;new&quot; title=&quot;Interpol&quot;&gt;Interpol's&lt;/a&gt; Daniel Kessler insists to &lt;a href=&quot;http://theedge.bostonherald.com/musicNews/view.bg?articleid=48417&quot; target=&quot;new&quot; title=&quot;Boston Herald vs Interpol&quot;&gt;&lt;i&gt;The Boston Herald&lt;/i&gt;&lt;/a&gt; that &quot;there is no sound as far as Interpol goes&quot;, thereby confirming the guy has never actually listened to any of his own records.  Remarkable.  From &lt;a href=&quot;http://blog.largeheartedboy.com&quot; target=&quot;new&quot; title=&quot;LHB&quot;&gt;Largehearted Boy&lt;/a&gt;.&lt;br /&gt;
&lt;br /&gt;
Hey, are Americans not on holiday today?  I thought is was Columbus Day or something, but everyone seems to be at work like normal.  Aww.  Happy Thanksgiving to all the hosers out there.&lt;br /&gt;
&lt;br /&gt;
np - &lt;a href=&quot;http://www.americanmusicclub.com&quot; target=&quot;new&quot; title=&quot;AMC&quot;&gt;American Music Club&lt;/a&gt; / &lt;i&gt;1984-1995&lt;/i&gt; </description>
     <pubDate>Mon, 11 Oct 2004 10:14:16 EST</pubDate>
     <guid>http://www.chromewaves.net/?itemid=1468</guid>
</item>
<item>
     <title>All These Telescopic Poems</title>
     <link>http://www.chromewaves.net/?itemid=1467</link>
     <description>  &lt;img src=&quot;http://www.chromewaves.net/images/interface/wilcoMasseyHall.jpg&quot; title=&quot;Wilco at Massey Hall&quot; class=&quot;blogPhoto&quot;&gt;So you think I'd be excited for last night's &lt;a href=&quot;http://www.wilcoworld.net&quot; target=&quot;new&quot; title=&quot;Wilco&quot;&gt;Wilco&lt;/a&gt; concert at Massey Hall, right?  And I was, very much so, but I was also apprehensive.  After all - this show was coming barely two months after their Mod Club show, which I declared &lt;a href=&quot;http://www.chromewaves.net/index.php?itemid=1378&quot; target=&quot;new&quot; title=&quot;Chromewaves vs Wilco&quot;&gt;&quot;the best show I have ever seen&quot;&lt;/a&gt;... what could they do for an encore?&lt;br /&gt;
&lt;br /&gt;
It's probably a good thing that Massey Hall is a dramatically different venue from The Mod Club - by virtue of the environment, a different sort of vibe was almost guaranteed.  Besides having almost five times the capacity, it's also a proper seated theatre with the best sound in the city.  However, that much-vaunted sound system seemed woefully absent when the band took the stage at nine sharp.  Howling feedback punctuated the first three songs of the set, prompting Jeff Tweedy to fess up that the band had, in fact, skipped soundcheck that day and was now paying the price for their laziness.  Sheepishly apologizing and promising an extra-long set to compensate, they let the sound crew sort things out and carried on with no more sonic gremlinery.&lt;br /&gt;
&lt;br /&gt;
That did, however, set the tone for a most peculiar evening.    After Mikael Jorgenson accidentally triggered the sample opening for &quot;Shot In The Arm&quot; one song too early, Jeff jokingly apologized for &quot;the least professional show of this tour&quot;.  He also had to deal with an audience member who chose to run right to the front of the stage and try to engage Jeff in... something.  Jeff was clearly perplexed by the incident and the mook stood there for all of &quot;Hell Is Chrome&quot; only to be shooed back to his seat by security after some of his buddies joined him up front.  Otherwise they just seemed to be having a good time on this, the second-last stop on this leg of their North American tour.  I was mildly disappointed that the setlist was very similar to the August show (&lt;A href=&quot;http://wilcobase.com/event.php?event_key=795&quot; target=&quot;new&quot; title=&quot;October setlist&quot;&gt;last night's setlist&lt;/a&gt; vs &lt;a href=&quot;http://wilcobase.com/event.php?event_key=773&quot; target=&quot;new&quot; title=&quot;August setlist&quot;&gt;August's setlist&lt;/a&gt;), but I suppose that it was only fair since more than 2000 of the people in attendance hadn't been at that show and hadn't seen the &lt;i&gt;Ghost&lt;/i&gt; material performed live yet.  &lt;br /&gt;
&lt;br /&gt;
Things got more interesting in the first encore, which consisted of the two most contentious songs from &lt;i&gt;A Ghost Is Born&lt;/i&gt;.  &quot;Less Than You Think&quot; was a revelation, performed as a beautiful country-ish lament worlds removed from the static-y sonic experiment of its album form.  The still managed to tack several minutes of noise onto the end, however, before launching into &quot;Spiders&quot; - ably performed but not as incendiary as the Mod Club show.  The second encore consisted mainly of &lt;i&gt;Mermaid Avenue&lt;/i&gt; material (in addition to &quot;The Late Greats&quot;) but the main highlight was the guest appearance on keys by Garth Hudson of &lt;a href=&quot;http://theband.hiof.no/&quot; target=&quot;new&quot; title=&quot;The Band&quot;&gt;The Band&lt;/a&gt;.  The final encore, kept short by a firm curfew from the venue, paired up the rocktacular &quot;I'm A Wheel&quot; with the gorgeously pensive &lt;a href=&quot;http://www.allmusic.com/cg/amg.dll?p=amg&amp;searchlink=BILL|FAY&amp;uid=MIDMR0410100119&amp;sql=11:xlv8b5m4tsqa~T0&quot; target=&quot;new&quot; title=&quot;Bill Fay&quot;&gt;Bill Fay&lt;/a&gt; number &quot;Be Not So Fearful&quot;, which was an election-year dedication to any Americans in the audience.&lt;br /&gt;
&lt;br /&gt;
So all in all - better than the August show?  No.  A disappointment?  God no.  It was still a superbly entertaining concert and if anything, it made me appreciate the opportunity I had to see them really tear it up in a club setting.  I can't imagine they'll be playing anything smaller than theatres in the forseeable future.  I will say this about a seated theatre, though - it's much easier to get good low light photographs (less moving around), though it does limit the number of vantage points you have for getting shots.  Being front row certainly helps, of course... &lt;a href=&quot;http://www.chromewaves.net/concertPhotos.php?concertPhotosID=56&quot;  title=&quot;Wilco in Toronto&quot;&gt;Check em out&lt;/a&gt;.&lt;br /&gt;
&lt;br /&gt;
np - &lt;a href=&quot;http://www.thefieryfurnaces.com&quot; target=&quot;new&quot; title=&quot;The Fiery Furnaces&quot;&gt;The Fiery Furnaces&lt;/a&gt; / &lt;i&gt;Blueberry Boat&lt;/i&gt; </description>
     <pubDate>Sun, 10 Oct 2004 09:50:49 EST</pubDate>
     <guid>http://www.chromewaves.net/?itemid=1467</guid>
</item>
<item>
     <title>Bands, Those Funny Little Plans That Never Work Quite Right</title>
     <link>http://www.chromewaves.net/?itemid=1466</link>
     <description>  &lt;img src=&quot;http://www.chromewaves.net/images/interface/digTheMovie.jpg&quot; title=&quot;Dig!&quot; class=&quot;blogPhoto&quot;&gt;When I got up yesterday morning, I knew pretty much nothing of &lt;a href=&quot;http://www.brianjonestownmassacre.com/&quot; target=&quot;new&quot; title=&quot;BJM&quot;&gt;The Brian Jonestown Massacre&lt;/a&gt; and I knew that I didn't like &lt;a href=&quot;http://www.dandywarhols.com/&quot; target=&quot;new&quot; title=&quot;The Dandy Warhols&quot;&gt;The Dandy Warhols&lt;/a&gt;.  After seeing &lt;A href=&quot;http://www.digthemovie.com&quot; target=&quot;new&quot; title=&quot;Dig!&quot;&gt;&lt;i&gt;Dig!&lt;/i&gt;&lt;/a&gt; last night, I know that BJM mastermind Anton Newcombe is a total nutbar and I really don't like the Dandy Warhols.  The documentary film follows the two bands over the course of seven years, tracking them from total obscurity to world stardom, in the case of the Dandys, and cult obscurity, in the case of the Massacre.  The Dandy Warhols come off as the epitome of vacuous fashion victims, eager - even desperate - to play the major label game to and make a grab for that brass ring.  It's especially surprising considering that Dandy's frontman Courtney Taylor acts as the film's narrator and doesn't seem at all self conscious about being cast as the artistically bankrupt but commercially successful foil.  In contrast, the BJM are portrayed as constantly teetering on the edge of self-immolation, despite Newcombe's acknowledged musical brilliance.  Particularly entertaining was Newcombe's decision to start a public feud with the Dandy's for publicity purposes without actually informing the other band of his plan.  At one point, he sends each of the Dandy Warhols shotgun shells with their names on them.  They got restraining orders.  Regardless of the original intent, the film is pretty much a documentary on Newcombe, and understandably so - he's utterly fascinating to watch, with his rages, rants and generally over-the-top behaviour.  Not surprisingly, &lt;a href=&quot;http://www.brianjonestownmassacre.com/dig_statement.html&quot; target=&quot;new&quot; title=&quot;BJM vs Dig!&quot;&gt;Newcombe disavows the film&lt;/a&gt; and the way he's portrayed in the film, and while he probably has a fair point about context, the video doesn't lie.  But if you want to see for yourself, the Brian Jonestown Massacre is at Lee's Palace on October 31.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.columbusalive.com/2004/20041006/100604/10060401.html&quot; target=&quot;new&quot; title=&quot;Columbus Alive vs DCFC&quot;&gt;&lt;i&gt;Columbus Alive&lt;/i&gt;&lt;/a&gt; talk to Ben Gibbard of &lt;a href=&quot;http://www.deathcabforcutie.com&quot; target=&quot;new&quot; title=&quot;DCFC&quot;&gt;Death Cab&lt;/a&gt; about why &lt;i&gt;The Photo Album&lt;/i&gt; didn't work, why &lt;i&gt;Transatlanticism&lt;/i&gt; does and the inevitability of losing their fanbase by growing their fanbase.  From &lt;A href=&quot;http://www.donewaiting.com&quot; target=&quot;new&quot; title=&quot;Donewaiting&quot;&gt;Donewaiting&lt;/a&gt;.&lt;br /&gt;
&lt;br /&gt;
David O Russell tells &lt;a href=&quot;http://www.thestar.com/NASApp/cs/ContentServer?pagename=thestar/Layout/Article_Type1&amp;c=Article&amp;cid=1097145046062&amp;call_pageid=968867495754&amp;col=969483191630&quot; target=&quot;new&quot; title=&quot;Toronto Star vs David O Russell&quot;&gt;&lt;i&gt;The Toronto Star&lt;/i&gt;&lt;/a&gt; that he's dead serious about everything in his new screwball existential comedy &lt;a href=&quot;http://www2.foxsearchlight.com/huckabees/&quot; target=&quot;new&quot; title=&quot;I Heart Huckabees&quot;&gt;&lt;i&gt;I Heart Huckabees&lt;/i&gt;&lt;/a&gt;.&lt;br /&gt;
&lt;br /&gt;
So I suppose I should make the formal announcement that &lt;a href=&quot;http://www.lakeholiday.net&quot; target=&quot;new&quot; title=&quot;Lake Holiday&quot;&gt;Lake Holiday&lt;/a&gt; is no more.  In what may have been the most painless and amicable band dissolution ever, it was mutually decided that in addition to numerous practical and logistical hurdles, the spark had dwindled in the last few months and that it was probably time to move on.  The record will still be coming out eventually in some form and there may be a performance to celebrate it, but as an ongoing concern and in anything resembling its current incarnation, after almost three years, Lake Holiday is done.  I'm obviously saddened by all this, but you know what they say about doors closing and windows opening and all that jazz.  Thanks to everyone who's supported us over the duration, it was really appreciated.&lt;br /&gt;
&lt;br /&gt;
So what next?  Well, I need a band.  I've still got the rehearsal space and would like an excuse to hold onto it, which basically means needing people to play with.  I'm not entirely sure how I'll go about that - it took me such a long time to find this band, I'm not especially looking forward to it.  It's like I have to dust off my musical resume and go applying for jobs, or starting to date again after a divorce.  On the other hand, the idea of maybe trying something new with different musicians is appealing.   I'll have to take a little time and figure out what I want to do, and then we'll see what happens... Psst - if anyone in the Toronto area is looking for a guitarist with modest abilities and a pretty eclectic range of interests and influences, drop me a line.  Thanks.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.wilcoworld.net&quot; target=&quot;new&quot; title=&quot;Wilco&quot;&gt;Wilco&lt;/a&gt; tonight!  That should recharge my creative batteries...&lt;br /&gt;
&lt;br /&gt;
np - &lt;a href=&quot;http://www.americanmusicclub.com&quot; target=&quot;new&quot; title=&quot;AMC&quot;&gt;American Music Club&lt;/a&gt; / &lt;i&gt;Love Songs For Patriots&lt;/i&gt; </description>
     <pubDate>Sat, 09 Oct 2004 09:20:33 EST</pubDate>
     <guid>http://www.chromewaves.net/?itemid=1466</guid>
</item>
<item>
     <title>Bramble Rose</title>
     <link>http://www.chromewaves.net/?itemid=1465</link>
     <description>  &lt;img src=&quot;http://www.chromewaves.net/images/interface/tiftMerritt.jpg&quot; title=&quot;Tift Merritt in Toronto&quot; class=&quot;blogPhoto&quot;&gt;I had decided to go see &lt;A href=&quot;http://www.tiftmerritt.com&quot; target=&quot;new&quot; title=&quot;Tift Merritt&quot;&gt;Tift Merritt&lt;/a&gt; at Lee's last night some time before I knew I'd have a cold, so I briefly considered ditching in favour of staying home and sleeping.  Eventually, I elected to dope myself up on medication and head down anyway and I'm glad I did.  I liked her first album &lt;i&gt;Bramble Rose&lt;/i&gt; well enough but her new one, &lt;i&gt;Tambourine&lt;/i&gt;, is a far superior collection.  Some have criticized her for branching off from the pretty but rather formulaic alt.country of her debut, but her decision to add rock, soul and gospel into the mix has really paid off.  In addition to the honeyed twang her voice gives the countrier stuff, she's a very effective belter on the more up material, evoking at times Luncida or Emmylou.&lt;br /&gt;
&lt;br /&gt;
I had thought Lee's would be an overly large venue for her, and while it wasn't packed by any means, she drew a larger and more enthusiastic crowd than I'd expected.  Tift and the band's easy Southern charm made sure everyone was enjoying themselves, even when they were interrupted for several minutes early on by malfunctions in the keyboards department.  The set was an excellent mix of gentler, weepier numbers, some performed solo acoustic by Tift, and all-out electric rockers.  I was particularly interested to see her guitarist Brad Rice, who was just announced as part of the new &lt;a href=&quot;http://www.jayfarrar.net&quot; target=&quot;new&quot; title=&quot;Son Volt&quot;&gt;Son Volt&lt;/a&gt; lineup.  No question, the guy can play, but it was hard to picture the flashy and somewhat goofy guy onstage with Tift alongside the dour Jay Farrar.  We'll have to see how that turns out.  Anyway, it was a perfectly entertaining and enjoyable show, and I think I'd say that even if I hadn't been doped to the gills on antihistamines.&lt;br /&gt;
&lt;br /&gt;
More pics to come later - I tried shooting in RAW and they take ages to process. &lt;strong&gt;Update:&lt;/strong&gt; Pics are done, up &lt;a href=&quot;http://www.chromewaves.net/concertPhotos.php?concertPhotosID=55&quot; title=&quot;Tift Merritt in Toronto&quot;&gt;here&lt;/a&gt;.&lt;br /&gt;
&lt;br /&gt;
Also on the slate last night was the advance screening for &lt;a href=&quot;http://www2.foxsearchlight.com/huckabees/main_site/main.html&quot; target=&quot;new&quot; title=&quot;I Heart Huckabees&quot;&gt;&lt;i&gt;I Heart Huckabees&lt;/i&gt;&lt;/a&gt;, the new film from David O Russell.  This has been on my short list of most-anticipated movies all year, and I can give it a head-scratching thumbs up.  This movie is weird.  I mean, it's about an existential detective agency - how can it not be weird?  It's certainly the most original movie of the year, that's for sure.  I should admit that I have pretty much no background in philosophy, nihilism, existentialism or other such highbrow cosmic issues, so I had no idea if they were talking sense or smack.  I did glean enough from the dialogue to have a good enough understanding of what was going on to follow the film, however, and there were enough moments of laugh-out-loud comedy to keep me entertained, even if I may not have appreciated the broader context.  The top-notch cast (Jason Schwartzman, Dustin Hoffman, Lily Tomlin, Isabelle Huppert, Mark Wahlberg, Jude Law, Naomi Watts) all seem to be having a good time with the material, Hoffman and Tomlin as the husband-and-wife investigators, in particular.  It was also nice to see Schwartzman get a decent post-&lt;i&gt;Rushmore&lt;/i&gt; role though his unbelievably thick eyebrows were a little distracting.  It's not a film for everyone, very much a &quot;you get it or you don't&quot; proposition, but if you go and are willing to not shut off your mind for the duration, it could well be worthwhile.  If you're looking for a popcorn flick, however, keep walking.&lt;br /&gt;
&lt;br /&gt;
np - &lt;a href=&quot;http://www.missionofburma.com&quot; target=&quot;new&quot; title=&quot;Mission Of Burma&quot;&gt;Mission Of Burma&lt;/a&gt; / &lt;i&gt;Vs&lt;/i&gt; </description>
     <pubDate>Fri, 08 Oct 2004 10:31:32 EST</pubDate>
     <guid>http://www.chromewaves.net/?itemid=1465</guid>
</item>
<item>
     <title>Last Minute Shakedown</title>
     <link>http://www.chromewaves.net/?itemid=1463</link>
     <description>  &lt;img src=&quot;http://www.chromewaves.net/images/interface/sonVolt2.jpg&quot; title=&quot;Son Volt&quot; class=&quot;blogPhoto&quot;&gt;The final word has come down on the &lt;A href=&quot;http://www.jayfarrar.net&quot; target=&quot;new&quot; title=&quot;Jay Farrar&quot;&gt;Son Volt&lt;/a&gt; reunion, and it's this - Jay and the band name are back, but the Boquists and Mike Heidorn are not.  They were &quot;unable to reach acceptable business terms&quot; and the Son Volt lineup will now feature all-new players.  Says Jay:&lt;blockquote&gt;&quot;Times change, and so do people, I guess. While I was looking forward to the reunion aspect of working with those guys, it just wasn't meant to be. It'll be liberating to get down to work with a different group of musicians. I had always envisioned Son Volt as a vehicle for my songwriting and expected it to evolve over the years. When I reformed the original band this year to record our track for &lt;i&gt;Por Vida&lt;/i&gt; it seemed like we might be able to extend that two-day session into two years of recording and touring--but it doesn't look that way now.&lt;/blockquote&gt;There is naturally much grumbling from the faithful about using the Son Volt name with a whole new lineup (some are calling it &quot;Guns'N'Volts&quot; though I think &quot;Sons'N'Roses&quot; sounds better) - me, I don't know how I feel about it, necessarily.  I'm disappointed that things didn't work out but what's in a name, really?  I will wait and see what the music is like before giving it a 'yay' or 'nay'.  I do think they totally blew it in making the announcement before all i's were dotted and the t's crossed - they had gotten everyone so worked up that now it can't help but seem like a disappointment.  The negotiations and breakdown thereof absolutely should not have been done in public, now everyone just looks bad.  Regardless, the studio webcam will be going live on October 12, with the album hopefully coming out mid-next year.  There will also be an anthology compiling album cuts along with rare or unreleased material coming out around the same time for those still craving a taste of the original lineup.&lt;br /&gt;
&lt;br /&gt;
&lt;A href=&quot;http://www.fearofspeed.net/amc.html&quot; target=&quot;new&quot; title=&quot;FOS vs AMC&quot;&gt;Fear Of Speed&lt;/a&gt; talks to &lt;a href=&quot;http://www.americanmusicclub.com&quot; target=&quot;new&quot; title=&quot;AMC&quot;&gt;American Music Club&lt;/a&gt; drummer Tim Mooney and singer Mark Eitzel in separate interviews about how the reunion came about and the making of &lt;i&gt;Love Songs For Patriots&lt;/i&gt;.  Apparently Mark is having trouble making heads or tails of cascading style sheets for his website.  &lt;i&gt;Love Songs&lt;/i&gt; should be out everywhere very very shortly, if not already.  Get it.  They also have &lt;A href=&quot;http://www.fearofspeed.net/jessesykes.html&quot; target=&quot;new&quot; title=&quot;FOS vs Jesse Sykes&quot;&gt;a nice interview&lt;/a&gt; with &lt;a href=&quot;http://www.jessesykes.com&quot; target=&quot;new&quot; title=&quot;Jesse Sykes&quot;&gt;Jesse Sykes&lt;/a&gt;.  It's a nice site - why have I not heard of it before?&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://edition.cnn.com/2004/SHOWBIZ/Music/10/06/celeb.paul.westerberg.ap/&quot; target=&quot;new&quot; title=&quot;CNN vs Westerberg&quot;&gt;CNN&lt;/a&gt; talks to &lt;a href=&quot;http://members.aol.com/paulspage/&quot; target=&quot;new&quot; title=&quot;Paul Westerberg&quot;&gt;Paul Westerberg&lt;/a&gt; about &lt;i&gt;Folker&lt;/i&gt; and the 'Mats reunion that never was.  From &lt;A href=&quot;Http://blog.largeheartedboy.com&quot; target=&quot;new&quot; title=&quot;LHB&quot;&gt;Largehearted Boy&lt;/a&gt;.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://www.nowtoronto.com/issues/2004-10-07/music_feature2.php&quot; Target=&quot;new&quot; title=&quot;NOW vs Interpol&quot;&gt;&lt;i&gt;NOW&lt;/i&gt;&lt;/a&gt; and &lt;a href=&quot;http://www.eye.net/eye/issue/issue_10.07.04/music/interpol.html&quot; target=&quot;new&quot; title=&quot;eye vs Interpol&quot;&gt;&lt;i&gt;eye&lt;/i&gt;&lt;/a&gt; both profile &lt;a href=&quot;http://www.interpolny.com&quot; target=&quot;new&quot; title=&quot;Interpol&quot;&gt;Interpol&lt;/a&gt; in advance of their show at The Docks next Wednesday.  And if that's not enough Interpol for you, bassist Carlos Dengler will be doing a DJ set at the Dance Cave that night at 10:00, cover $8.&lt;br /&gt;
&lt;br /&gt;
A couple shows... UK buzzband of the moment &lt;A href=&quot;http://www.razorlight.co.uk/site.php&quot; target=&quot;new&quot; title=&quot;Razorlight&quot;&gt;Razorlight&lt;/a&gt; are at Lee's Palace November 4, tickets on sale now for $12.50, and &lt;a href=&quot;http://www.theunicorns.net&quot; target=&quot;new&quot; title=&quot;The Unicorns&quot;&gt;The Unicorns&lt;/a&gt; play an all-ages Hallowe'en show at the Vatikan (no I don't know where that is) October 27, cover $8.  And some ticket prices - &lt;a href=&quot;http://www.fuzzywuzzy.com&quot; target=&quot;new&quot; title=&quot;Luna&quot;&gt;Luna&lt;/a&gt; at Lee's November 7 is $17.50, &lt;A href=&quot;http://www.matthew-sweet.com&quot; target=&quot;new&quot; title=&quot;Matthew Sweet&quot;&gt;Matthew Sweet&lt;/a&gt; and &lt;a href=&quot;http://www.velvetcrushrockgroup.com&quot; target=&quot;new&quot; title=&quot;Velvet Crush&quot;&gt;Velvet Crush&lt;/a&gt; at the Mod Club November 8 is $25 (ouch!), &lt;a href=&quot;http://www.sufjan.com/&quot; target=&quot;new&quot; title=&quot;Sufjan Stevens&quot;&gt;Sufjan Stevens&lt;/a&gt; at Lee's November 16 it $14.  All on sale now.  Doing the math for all the tickets I need to get, including those for other people, and... ow.  Better hit a bank machine.  &lt;strong&gt;Update:&lt;/strong&gt; Razorlight appears to have been cancelled.  Don't ask me, I don't know.&lt;br /&gt;
&lt;br /&gt;
np - &lt;a href=&quot;http://www.sonicyouth.com&quot; target=&quot;new&quot; title=&quot;Sonic Youth&quot;&gt;Sonic Youth&lt;/a&gt; / &lt;i&gt;Sonic Nurse&lt;/i&gt; </description>
     <pubDate>Thu, 07 Oct 2004 09:44:40 EST</pubDate>
     <guid>http://www.chromewaves.net/?itemid=1463</guid>
</item>
<item>
     <title>The Universe Is Expanding</title>
     <link>http://www.chromewaves.net/?itemid=1461</link>
     <description>  &lt;img src=&quot;http://www.chromewaves.net/images/interface/deanWareham.jpg&quot; title=&quot;Dean Wareham's Top 10 List&quot; class=&quot;blogPhoto&quot;&gt;Dean Wareham has posted his reasons for retiring &lt;a href=&quot;http://www.fuzzywuzzy.com&quot; target=&quot;new&quot; title=&quot;Luna&quot;&gt;Luna&lt;/a&gt; on their website, in a playful and enigmatic top-10 list format:&lt;br /&gt;
&lt;br /&gt;
1. Rock and Roll is killing my life.&lt;br /&gt;
2. The Universe is Expanding.&lt;br /&gt;
3. There are too many bands out there, travelling around, singing their songs etc.&lt;br /&gt;
4. Too much time spent in 15-passenger vans. According to 20/20, these things flip over.&lt;br /&gt;
5. Too many hands to shake, that means germs.&lt;br /&gt;
6. Too many dinners at Wendy's.&lt;br /&gt;
7. People are dying in Iraq.&lt;br /&gt;
8. This is what bands do (with a few exceptions, like R.E.M. and Metallica, and the Rolling Stones). Those bands, however, are multibillion dollar corporations. You don't break that up unless the government forces you to.&lt;br /&gt;
9. Hotel Electravision.&lt;br /&gt;
10. Time to Quit.&lt;br /&gt;
&lt;br /&gt;
In other words, he's tired.  Understandable - he's been doing the touring musician thing for sixteen years.  But not too tired to release swan song &lt;i&gt;Rendezvous&lt;/i&gt; on October 26 and hit Lee's Palace on November 7.&lt;br /&gt;
&lt;br /&gt;
Thanks to &lt;a href=&quot;http://www.morecowbell.net&quot; target=&quot;new&quot; title=&quot;More Cowbell&quot;&gt;Morecowbell.net&lt;/a&gt; for the tip-off that the long-rumoured (&lt;A href=&quot;http://www.chromewaves.net/index.php?itemid=1295&quot; title=&quot;Matthew Sweet rumour-mongering&quot;&gt;by me&lt;/a&gt;, mostly) &lt;A href=&quot;http://www.matthew-sweet.com&quot; target=&quot;new&quot; title=&quot;Matthew Sweet&quot;&gt;Matthew Sweet&lt;/a&gt;/&lt;a href=&quot;http://www.velvetcrushrockgroup.com&quot; target=&quot;new&quot; title=&quot;Velvet Crush&quot;&gt;Velvet Crush&lt;/a&gt; tour is finally happening and it's stopping at the Mod Club in Toronto on November 8.  It's expected that Matthew will play guitar with the Crush and they will in turn act as his backing band.  &lt;A href=&quot;http://www.theweakerthans.org&quot; target=&quot;new&quot; title=&quot;Weakerthans&quot;&gt;The Weakerthans&lt;/a&gt; are also supporting on at least one other date on the tour, but there's no information as to whether that's a one-off or an ongoing thing - more information as it comes.  My formerly quiet November has now been transformed into a tsunami of rock - six shows in ten days, two of them in a foreign country, eight in November altogether, and quite possible more to come.  Wheee.&lt;br /&gt;
&lt;br /&gt;
That's all I got for today.  Come back tomorrow.&lt;br /&gt;
&lt;br /&gt;
&lt;strong&gt;Update:&lt;/strong&gt; Okay, one more thing - did anyone else see the Vice-Presidential debate last night?  Notice when Cheney told people to go to &lt;a href=&quot;http://www.factcheck.com&quot; target=&quot;new&quot; title=&quot;Factcheck.com&quot;&gt;Factcheck.com&lt;/a&gt;?  He better hope that the viewership was as apathetic as everyone says, cause that's not the website he meant to refer them to... Go - it's pretty funny.  &lt;a href=&quot;http://slate.msn.com/id/2107809/&quot; target=&quot;new&quot; title=&quot;Slate vs Cheney&quot;&gt;Slate&lt;/a&gt; has a full writeup on the gaffe.&lt;br /&gt;
&lt;br /&gt;
np - &lt;a href=&quot;http://www.drivebytruckers.com&quot; target=&quot;new&quot; title=&quot;Drive By Truckers&quot;&gt;Drive By Truckers&lt;/a&gt; / &lt;i&gt;The Dirty South&lt;/i&gt; </description>
     <pubDate>Wed, 06 Oct 2004 09:37:40 EST</pubDate>
     <guid>http://www.chromewaves.net/?itemid=1461</guid>
</item>
<item>
     <title>A Sea Black With Ink</title>
     <link>http://www.chromewaves.net/?itemid=1460</link>
     <description>  &lt;img src=&quot;http://www.chromewaves.net/images/interface/wilco2.jpg&quot; title=&quot;Wilco&quot; class=&quot;blogPhoto&quot;&gt;Well that was one crazy-ass traffic spike yesterday.  Yow.&lt;br /&gt;
&lt;br /&gt;
Just for the record, I'm writing this post in a not inconsiderable amount of discomfort.  I seem to have pinched an incredibly painful nerve in my back, I had another muscle spasm in my left calf the other night and I'm coming down with a cold.  NOT HAVING A GOOD TIME.  But I'm here for you.&lt;br /&gt;
&lt;br /&gt;
Haven't had much &lt;a href=&quot;http://www.wilcoworld.net&quot; target=&quot;new&quot; title=&quot;Wilco&quot;&gt;Wilco&lt;/a&gt; content lately... let's rectify that.  I realize my jones for Jeff and the boys is a bit of a running joke, but the Britney-watch has sorta been done to death.  I need a different angle.  Anyway:&lt;br /&gt;
&lt;br /&gt;
Firstly - much sleuthing has revealed the openers for this Saturday's show at Massey Hall will be The Priscillas.  Not &lt;a href=&quot;http://www.thepriscillas.co.uk/&quot; target=&quot;new&quot; title=&quot;The Priscillas UK&quot;&gt;these Priscillas&lt;/a&gt;, but &lt;a href=&quot;http://www.thepriscillas.net/&quot; target=&quot;new&quot; title=&quot;The Priscillas Canada&quot;&gt;THESE Priscillas&lt;/a&gt;.  Apparently they're a group of local scenesters (Tara from Elevator, Colleen from &lt;a href=&quot;http://www.bydivineright.com&quot; target=&quot;new&quot; title=&quot;By Divine Right&quot;&gt;By Divine Right&lt;/a&gt;) who don beehive wigs and perform covers and originals.  Should be interesting.&lt;br /&gt;
&lt;br /&gt;
Secondly - &lt;a href=&quot;http://chattanoogapulse.com/newsphp/index.php?id=552&quot; target=&quot;new&quot; title=&quot;Chattnooga Pulse vs Wilco&quot;&gt;&lt;i&gt;The Chattanooga Pulse&lt;/i&gt;&lt;/a&gt; nabs not only a terrific interview with Jeff Tweedy about the tour, his anti-Bush rants and religion, but a crank call to the writer's girlfriend.&lt;br /&gt;
&lt;br /&gt;
Thirdly - the CD tracks from &lt;A href=&quot;http://www.thewilcobook.com&quot; target=&quot;new&quot; title=&quot;Wilco Book&quot;&gt;&lt;i&gt;The Wilco Book&lt;/i&gt;&lt;/a&gt; have officially leaked.  I'm not going to tell you where to get them, but they're out there.  And they're... interesting.&lt;br /&gt;
&lt;br /&gt;
And finally, &lt;A href=&quot;http://www.bradleysalmanac.com/blogger.html&quot; target=&quot;new&quot; title=&quot;Bradley's Almanac&quot;&gt;Bradley's Almanac&lt;/a&gt; has an mp3 of their performance of &quot;Theologians&quot; from &lt;i&gt;Late Night With Conan O'Brien&lt;/i&gt; last week.  I've never heard John Stirratt's backing vocals so high in a mix before.&lt;br /&gt;
&lt;br /&gt;
&amp;lt;/Wilco content&amp;gt;&lt;br /&gt;
&lt;br /&gt;
This week, I rule the school... press, anyway.  &lt;a href=&quot;http://www.chromewaves.net/concertPhotos.php?concertPhotosID=52&quot; title=&quot;Arcade Fire pics&quot;&gt;My pics&lt;/a&gt; from Friday's &lt;A href=&quot;http://www.arcadefire.com&quot; target=&quot;new&quot; title=&quot;Arcade Fire&quot;&gt;Arcade Fire&lt;/a&gt; show will be gracing both University of Toronto newspapers this week - &lt;A href=&quot;http://www.thevarsity.ca&quot; target=&quot;new&quot; title=&quot;The Varsity&quot;&gt;&lt;i&gt;The Varsity's&lt;/i&gt;&lt;/a&gt; current issue is borrowing one pic and &lt;a href=&quot;http://thenewspaper.ca/&quot; target=&quot;new&quot; title=&quot;The Newspaper&quot;&gt;&lt;i&gt;The Newspaper&lt;/i&gt;&lt;/a&gt; is running two other photos, including one for the cover, and my entire review in their next issue (out Thursday I think?).  Reminds me of my days writing for the University of Waterloo student rag, &lt;a href=&quot;http://imprint.uwaterloo.ca/&quot; target=&quot;new&quot; title=&quot;Imprint&quot;&gt;&lt;i&gt;The Imprint&lt;/i&gt;&lt;/a&gt;.  Sure, the free CDs and concerts were nice but I really did it to associate with someone - anyone - who wasn't an engineer for a change.  Didn't work, but hey.&lt;br /&gt;
&lt;br /&gt;
&lt;a href=&quot;http://enjoyment.independent.co.uk/music/interviews/story.jsp?story=567567&quot; target=&quot;new&quot; title=&quot;Independent vs Flaming Lips&quot;&gt;&lt;i&gt;The Independent&lt;/i&gt;&lt;/a&gt; gets Wayne Coyne to reflect a bit on the career of &lt;a href=&quot;http://www.flaminglips.com&quot; target=&quot;new&quot; title=&quot;The Flaming Lips&quot;&gt;The Flaming Lips&lt;/a&gt; and look ahead into the future.&lt;br /&gt;
&lt;br /&gt;
Great thanks to Dave Weiss who has graciously provided a much better quality mp3 of &lt;a href=&quot;http://www.curve.demon.co.uk/lush/&quot; target=&quot;new&quot; title=&quot;Lush&quot;&gt;Lush's&lt;/a&gt; cover of &quot;Outdoor Miner&quot;, the bonus cover for this week.  I've uploaded it so if you grabbed the lousy-quality one earlier this week, try it again.  Tangential thought - I really need to get some &lt;a href=&quot;http://www.pinkflag.com/&quot; Target=&quot;new&quot; title=&quot;Wire&quot;&gt;Wire&lt;/a&gt;.  &lt;i&gt;Pink Flag&lt;/i&gt; is the place to start, obviously?&lt;br /&gt;
&lt;br /&gt;
I won passes to see an advance screening of &lt;a href=&quot;http://www2.foxsearchlight.com/huckabees/main_site/main.html&quot; target=&quot;new&quot; title=&quot;I Heart Huckabees&quot;&gt;&lt;i&gt;I Heart Huckabees&lt;/i&gt;&lt;/a&gt; this Thursday from &lt;a href=&quot;http://www.nowtoronto.com&quot; target=&quot;new&quot; title=&quot;NOW&quot;&gt;&lt;i&gt;NOW&lt;/i&gt;&lt;/a&gt;!  Yay.  Reviews have been &lt;a href=&quot;http://www.metacritic.com/film/titles/ihearthuckabees/&quot; target=&quot;new&quot; title=&quot;Metacritic vs Huckabees&quot;&gt;somewhat&lt;/a&gt; &lt;a href=&quot;http://www.rottentomatoes.com/m/i_heart_huckabees/&quot; target=&quot;new&quot; title=&quot;Rotten Tomatos vs Huckabees&quot;&gt;mixed&lt;/a&gt;, but I'm looking forward to it anyway.  Watch for a review here Friday.&lt;br /&gt;
&lt;br /&gt;
np - &lt;a href=&quot;http://www.saturdaylooksgoodtome.com&quot; target=&quot;new&quot; title=&quot;SLGTM&quot;&gt;Saturday Looks Good To Me&lt;/a&gt; / &lt;i&gt;Every Night&lt;/i&gt; </description>
     <pubDate>Tue, 05 Oct 2004 09:29:51 EST</pubDate>
     <guid>http://www.chromewaves.net/?itemid=1460</guid>
</item>
</channel>
</rss>";

$start = time();
$i = 0;
for ($i = 0; $i < 20000; $i++)
{
    preg_match_all('/<title>([^<]*)/',$rss,$titles_arr);
    $arr = array();
    foreach ($titles_arr[1] as $title)
    {
        $title;
    }
}
$finish = time();

print ($finish - $start)." seconds for regexp PHP"
?>

