# GitHub Action to prove a failure still exists...
# * lxml still cannot be successfully installed on Python 3.11 on Windows.
# When this GitHub Action passes then it can be deleted.

name: pip_install_lxml
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  from_repo:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]  # [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2 libxslt-dev
      - run: pip install --upgrade pip
      - run: pip install --upgrade cython wheel
      - run: pip install .  # Trying to prove a failure (a negative)
      - if: success()  # Reverse success and failure.
        run: exit 1  # Install has succeed so this GitHub Action can be deleted.
      - if: failure()
        run: exit 0  # lxml still fails on Python 3.11 on Windows
  from_pypi:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]  # [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install --upgrade pip wheel
      - run: pip install lxml  # Trying to prove a failure (a negative)
      - if: success()  # Reverse success and failure.
        run: exit 1  # Install has succeed so this GitHub Action can be deleted.
      - if: failure()
        run: exit 0  # lxml still fails on Python 3.11 on Windows
